README.rst
docs/examples/02_coordinate_frames.rst
docs/examples/03_kinematic_model.rst
docs/examples/files/0x_load_robot_6.ghx
docs/examples/files/robot-artist-blender.py
docs/examples/files/robot-artist-grasshopper.ghx
docs/examples/files/robot-artist-rhino.py
docs/examples/files/robot.ghx
setup.py
src/compas_fab/artists/base.py
src/compas_fab/robots/robot.py
src/compas_fab/robots/semantics.py

Follow up of the rename on `compas` main

Rename `Robot` to `RobotModel`

---

src/compas_fab/robots/robot.py

Things that are not clear based on the current doc and figured out from asking questions.
Hoping to create a better doc little by little.

improve comments for better doc.

---

docs/examples/03_backends_ros/files/robot.ghx

C# usage for GH component.
No single quote for string.

fix single/double quotes issues of solver selector.

---

AUTHORS.rst

Added citation bib thing. This is how it renders in LaTeX:

Add citing

---

CHANGELOG.rst
docs/examples/03_backends_ros/files/robot.ghx
src/compas_fab/artists/base.py
src/compas_fab/ghpython/artists.py
src/compas_fab/rhino/artists.py
src/compas_fab/robots/robot.py

Several smaller changes, mainly moving functionality from `compas_fab.artists.BaseRobotArtist` to `compas.robots.RobotModel`. So this pull request is linked with another one.
The main advantage is to call forward_kinematics on the robot model and to have a bit of better divide between artist and model.
These are breaking, but easily fixable changes.

Update `compas_fab.artists.BaseRobotArtist` and `compas.robots.RobotModel`

---

CHANGELOG.rst
docs/reference/compas_fab.sensors.rst
src/compas_fab/__init__.py
src/compas_fab/sensors/__init__.py
src/compas_fab/sensors/baumer.py
src/compas_fab/sensors/exceptions.py
tasks.py

Formatting and cleanup update on `sensors.baumer` module.
Add `class PosConCM` for round object measurement.
+ also see unrelated change in tasks.py to run tests:
removed `ctx.run('pytest --doctest-module')`
added     `ctx.run('pytest --doctest-modules')`

Update sensors\baumer module

---

CHANGELOG.rst
src/compas_fab/backends/ros/planner_backend_moveit.py

Fix planner's initialization

---

src/compas_fab/robots/trajectory.py

fix doc_string bug.

---

setup.cfg

Numpy convention set for pydocstyle

---

CHANGELOG.rst
src/compas_fab/robots/constraints.py
src/compas_fab/robots/robot.py

``robot.constraints_from_configuration`` function edited to comply with new ``JointConstraint`` above and below tolerances

Joint constraint

---

CHANGELOG.rst
src/compas_fab/artists/base.py
src/compas_fab/robots/planning_scene.py

Suggestion for #142 
Change in a **backwards-compatible** manner.
Not if users are scaling the collision mesh before adding it to scene.
- ~~I have added tests that prove my fix is effective or that my feature works.~~ (Will do that when I write tests for whole module)

Use scale factor for CollisionMesh (suggestion for #142)

---

CONTRIBUTING.rst

Add paragraph about docstring style

---

src/compas_fab/utilities/file_io.py

documents parameters and returns

---

docs/examples/01_fundamentals/02_coordinate_frames.rst
docs/examples/03_backends_ros/01_ros_examples.rst
docs/examples/03_backends_ros/02_forward_and_inverse_kinematics.rst
docs/examples/03_backends_ros/03_collision_objects.rst
docs/examples/03_backends_ros/04_plan_motion.rst
docs/examples/04_backends_vrep/01_simulation_with_vrep.rst
src/compas_fab/robots/robot.py
src/compas_fab/utilities/file_io.py
tasks.py

Tiny doc fixes

---

CHANGELOG.rst
docs/examples/01_fundamentals/02_coordinate_frames.rst
src/compas_fab/robots/robot.py

Update `to_local_coords` and `to_world_coords` to `to_local_coordinates` and `to_world_coordinates` for consistency with compas core.

Consistency update

---

src/compas_fab/backends/ros/messages/control_msgs.py
src/compas_fab/backends/ros/messages/moveit_msgs.py
src/compas_fab/backends/ros/messages/services.py
src/compas_fab/backends/ros/messages/shape_msgs.py
src/compas_fab/backends/ros/messages/std_msgs.py

Were nagged by my pre-commit autopep8 hook so decided to open a PR for this. This is just adding a blank line between class docstring and following method.

autopep8 compas_fab/backends/ros/messages

---

src/compas_fab/robots/robot.py

get correct end effector

---

src/compas_fab/robots/robot.py

In order to quickly close out old PRs, I've recreated @tetov 's PR here (because git wasn't allowing me to fetch from the fork) having essentially rebased it on the head of the master branch.

robot docs

---

src/compas_fab/robots/planning_scene.py

add scaled to CollisionMesh and use in PlanningScene

---

docs/examples/03_backends_ros/01_ros_examples.rst
src/compas_fab/backends/ros/client.py

add context managerless ros example

---

setup.py
src/compas_fab/blender/artists.py
src/compas_fab/ghpython/artists.py
src/compas_fab/ghpython/path_planning.py
src/compas_fab/rhino/artists.py
src/compas_fab/rhino/install.py
src/compas_fab/rhino/uninstall.py

Addresses changes in rhino related imports in compas v0.16.3/4.

Compas update

---

CHANGELOG.rst
src/compas_fab/robots/configuration.py
src/compas_fab/robots/robot.py
src/compas_fab/robots/trajectory.py
tests/robots/test_configuration.py

Add merge method to Configuration

---

CHANGELOG.rst
src/compas_fab/ghpython/artists.py
src/compas_fab/rhino/uninstall.py
src/compas_fab/robots/robot.py
src/compas_fab/robots/semantics.py
tests/robots/test_semantics.py

Group state semantics

---

.github/workflows/ironpython.yml
tests/ipy_test_runner.py

Fix ipy build error

---

CHANGELOG.rst
docs/examples/02_description_models/02_robot.rst
docs/examples/02_description_models/files/02_robot_artist_grasshopper.ghx
docs/examples/02_description_models/files/02_robot_artist_grasshopper_panda.ghx
docs/examples/03_backends_ros/files/gh_robot_visualisation.py
src/compas_fab/robots/configuration.py
src/compas_fab/robots/robot.py

Here's a few very small fixes bundled in one PR.

Minor fixes

---

CHANGELOG.rst
src/compas_fab/robots/planning_scene.py

Fix bug in add_attached_tool

---

CHANGELOG.rst
src/compas_fab/robots/tool.py

Add tool name property

---

.github/workflows/deploy-n-publish.yml
docs/conf.py
docs/getting_started.rst
src/compas_fab/sensors/baumer.py

Fix broken links and automate checking

---

docs/getting_started.rst

Package update instructions. 

---

.github/workflows/deploy-n-publish.yml

Strip v from version tags for doc workflow

---

.github/workflows/deploy-n-publish.yml
docs/getting_started.rst

SSL works again so we should return to checking the links.  There was one that was broken.

Check links

---

.github/workflows/integration.yml

Minor fix to the integration tests workflow.

remove extraneous docker rm

---

.github/workflows/build.yml
.github/workflows/deploy-n-publish.yml
.github/workflows/integration.yml
.github/workflows/pr-checks.yml
CONTRIBUTING.rst
README.rst
src/compas_fab/__init__.py

Updated references of `master` to `main` (only when referring to branches, not changed the ROS master references)

Update references of master branch to main

---

CHANGELOG.rst
src/compas_fab/backends/ros/messages/std_msgs.py
tests/backends/ros/messages/test_std_msgs.py

Fix ROSmsg representation

---

CHANGELOG.rst
README.rst
setup.cfg
src/compas_fab/backends/ros/backend_features/move_it_inverse_kinematics.py
src/compas_fab/backends/ros/client.py
src/compas_fab/backends/ros/messages/__init__.py
src/compas_fab/backends/ros/messages/moveit_msgs.py
src/compas_fab/backends/ros/messages/ros_releases.py
src/compas_fab/backends/ros/messages/std_msgs.py

There were some minor tweaks required for the moveit planner to be compatible with ROS Noetic.

Add support for ROS Noetic

---

.bumpversion.cfg
docs/conf.py
docs/getting_started.rst

Main reason for this PR was the line added in `conf.py` to get rid of these annoying artifacts that appeared in the docs a while ago:

Update install instructions to match COMPAS

---

CHANGELOG.rst
src/compas_fab/robots/trajectory.py
tests/robots/test_trajectory.py

Fix JointTrajectoryPoint serialization

---

.github/workflows/build.yml
CHANGELOG.rst
setup.py

Add python 3.9 support

---

docs/examples/03_backends_ros/07_ros_create_urdf_ur5_with_measurement_tool.rst

Fix a minor typo

---

CHANGELOG.rst
src/compas_fab/backends/ros/messages/geometry_msgs.py
src/compas_fab/backends/ros/messages/std_msgs.py
tests/backends/ros/messages/test_std_msgs.py

Added some new ROS message types for convenience.

Some new ROS messages

---

src/compas_fab/robots/planning_scene.py

improved docs

---

docs/api/compas_fab.backends.rst
docs/api/compas_fab.robots.rst
docs/api/compas_fab.rst
docs/api/compas_fab.sensors.rst
docs/api/compas_fab.utilities.rst
docs/examples/04_backends_vrep/01_simulation_with_vrep.rst
docs/examples/04_backends_vrep/files/01_complete_path_planning_example.py
src/compas_fab/backends/__init__.py
src/compas_fab/backends/pybullet/planner.py
src/compas_fab/backends/ros/planner.py
src/compas_fab/backends/vrep/planner.py
src/compas_fab/robots/__init__.py
src/compas_fab/robots/inertia.py
src/compas_fab/robots/planning_scene.py
src/compas_fab/robots/rfl.py
src/compas_fab/robots/tool.py
src/compas_fab/robots/trajectory.py
src/compas_fab/sensors/__init__.py
src/compas_fab/utilities/__init__.py
src/compas_fab/utilities/numbers.py
tests/api/compas_fab_api.json
tests/api/compas_fab_api_ipy.json
tests/api/test_api_completeness.py
tests/api/test_api_stability.py

replaced dynamic definitions of __all__ and added tests

---

CHANGELOG.rst

added new line to changelog

---

CHANGELOG.rst
docs/examples/06_backends_kinematics/files/02_iter_ik_pybullet.py
docs/examples/06_backends_kinematics/files/03_iter_ik_analytic_pybullet.py
docs/examples/06_backends_kinematics/files/04_cartesian_path_analytic_pybullet.py
src/compas_fab/backends/__init__.py
src/compas_fab/backends/kinematics/__init__.py
src/compas_fab/backends/kinematics/analytical_inverse_kinematics.py

Added small fixes to the recently merged PR "ik analytical"

Ik analytical addon

---

docs/examples/07_reachability_map/01_reachability_map.rst

small typo in 01_reachability_map.rst

---

docs/examples/07_reachability_map/03_rp_2D.rst

small typo in 03_rp_2D.rst

---

CHANGELOG.rst
src/compas_fab/backends/ros/__init__.py
src/compas_fab/ghpython/components/Cf_RosTopicPublish/code.py
src/compas_fab/ghpython/components/Cf_RosTopicSubscribe/code.py

Fix ROSmsg import on pub/sub components

---

CHANGELOG.rst
src/compas_fab/ghpython/components/Cf_AttachTool/metadata.json
src/compas_fab/ghpython/components/Cf_AttachedCollisionMesh/metadata.json
src/compas_fab/ghpython/components/Cf_CollisionMesh/metadata.json
src/compas_fab/ghpython/components/Cf_ConfigMerge/metadata.json
src/compas_fab/ghpython/components/Cf_ConfigZero/metadata.json
src/compas_fab/ghpython/components/Cf_ConstraintsFromPlane/metadata.json
src/compas_fab/ghpython/components/Cf_InverseKinematics/metadata.json
src/compas_fab/ghpython/components/Cf_PlanCartesianMotion/metadata.json
src/compas_fab/ghpython/components/Cf_PlanMotion/metadata.json
src/compas_fab/ghpython/components/Cf_PlanningScene/metadata.json
src/compas_fab/ghpython/components/Cf_RosConnect/metadata.json
src/compas_fab/ghpython/components/Cf_RosRobot/metadata.json
src/compas_fab/ghpython/components/Cf_RosTopicPublish/metadata.json
src/compas_fab/ghpython/components/Cf_RosTopicSubscribe/metadata.json
src/compas_fab/ghpython/components/Cf_VisualizeRobot/metadata.json
src/compas_fab/ghpython/components/Cf_VisualizeTrajectory/metadata.json

Tiny PR: changed GH components to default to "icon display":

Default to icon display components

---

README.rst

Add badges for download stats

---

CHANGELOG.rst
src/compas_fab/ghpython/components/Cf_ConstraintsFromPlane/code.py
src/compas_fab/ghpython/components/Cf_InverseKinematics/code.py
src/compas_fab/ghpython/components/Cf_PlanCartesianMotion/code.py
src/compas_fab/ghpython/components/__init__.py

Use the core function for this now that it is there.

Use compas_rhino.conversions for frame coercion

---

CHANGELOG.rst
src/compas_fab/robots/trajectory.py

fix: `Trajectory` inherits from `Data` to resolve serialization bug with latest compas encoders

---

CHANGELOG.rst
tasks.py

Added a `(COMPAS-FAB) ` prefix to all GH components to make it easier to quickly tell them apart from similarly named components.

Gh package name

---

.github/workflows/deploy-n-publish.yml

Tiny PR, just bump version of componentizer.

Use v2 componentizer

---

AUTHORS.rst
CHANGELOG.rst
src/compas_fab/robots/time_.py
tests/robots/test_duration.py

- [X ] Update to Duration class to take floats as sec variable
- [ X] I added a line to the `CHANGELOG.rst` file in the `Unreleased` section under the most fitting heading (e.g. `Added`, `Changed`, `Removed`).
- [ X] I ran all tests on my computer and it's all green (i.e. `invoke test`).
- [ X] I ran lint on my computer and there are no errors (i.e. `invoke lint`).
- [X ] I have added tests that prove my fix is effective or that my feature works.
- [ X] I have added necessary documentation (if appropriate)

Duration class change, take float as sec variable

---

CHANGELOG.rst
src/compas_fab/backends/kinematics/solvers/spherical_wrist.py

Backwards-compatible fix for tangent_points_to_circle_xy

---

.github/workflows/build.yml
.github/workflows/integration.yml
.github/workflows/ironpython.yml
.github/workflows/pr-checks.yml

@gonzalocasas please take a look

Update build.yml to run on all Pull Requests
