.travis.yml, CHANGELOG.rst, src/compas_fab/backends/__init__.py, src/compas_fab/backends/ros/client.py, src/compas_fab/backends/ros/messages/control_msgs.py, src/compas_fab/backends/ros/messages/moveit_msgs.py, src/compas_fab/backends/ros/messages/trajectory_msgs.py, src/compas_fab/backends/ros/planner_backend_moveit.py, src/compas_fab/backends/tasks.py, src/compas_fab/robots/robot.py, src/compas_fab/robots/trajectory.py
Changed the ROS client trajectory follower to handle (in a backwards-compatible way) arguments of generic trajectory type.
=> Handle generic trajectory arguments on the ROS client trajectory follower

CHANGELOG.rst, src/compas_fab/robots/robot.py
Rather simplistic fix for robots that are not attached to any fixed joint, like world or similar.
=> Assume a robot without a parent joint on its base is on the worldXY origin

CHANGELOG.rst, docs/examples/01_fundamentals/01_frame_and_transformation.rst, docs/examples/01_fundamentals/02_coordinate_frames.rst, docs/examples/03_backends_ros/files/02_forward_kinematics.py, docs/examples/03_backends_ros/files/02_forward_kinematics_ros.py, docs/examples/03_backends_ros/files/robot.ghx, setup.py, src/compas_fab/robots/constraints.py, src/compas_fab/robots/robot.py
This updates `compas_fab` dependency on `compas` to the latest release and changes the `Robot`'s `represent_*` methods to match the new naming.
This is a breaking change because the robot's methods have been renamed, without fallback to the previous names.
=> Bump dependency to compas 0.10.0

CHANGELOG.rst, docs/backends/files/panda-demo/docker-compose.yml, src/compas_fab/artists/base.py, src/compas_fab/backends/ros/fileserver_loader.py
This PR fixes several issues that are visible when parsing Panda model:
This is the final result, the panda model is being read directly off of ROS via the file loader server:
=> Add support for DAE files and multiple meshes per mesh descriptor

CHANGELOG.rst, docs/examples/03_backends_ros/files/02_forward_kinematics_ros_loader.py, docs/examples/03_backends_ros/files/02_inverse_kinematics_ros_loader.py, docs/examples/03_backends_ros/files/04_plan_cartesian_motion_ros_loader.py, docs/examples/03_backends_ros/files/04_plan_motion_ros_loader.py, docs/examples/03_backends_ros/files/robot-playground.ghx, src/compas_fab/backends/ros/client.py, src/compas_fab/backends/ros/fileserver_loader.py
Added `load_robot` to `RosClient` to make it trivial to load robots from a running ROS setup.
=> Simplify load robot from ROS

CHANGELOG.rst, src/compas_fab/__init__.py
Matching the behavior of `compas`, now `compas_fab` also includes the git commit hash in the `compas_fab.__version__` identifier if installed from source.
=> Adding commit hash to version

CHANGELOG.rst, src/compas_fab/backends/ros/fileserver_loader.py
DAE supports multiple geometric primitives to define meshes, this PR adds support for one more (`polylist`), and raises an exception if the primitive is not yet supported.
=> Fix DAE parser to handle polylist-based  meshes

.travis.yml, requirements-dev.txt, setup.cfg, tasks.py
I though coverage analysis would be helpful for assessing the state of our documentation. This adds a switch to `invoke test` to run the plugin [pytest-cov](https://github.com/pytest-dev/pytest-cov) when testing.
I also switched the default value for the keyword argument `doctest` to `False` to match the command argument help. The Travis build on Linux runs doctest using `pytest --doctest-modules` so I don't think the CI setup will be impacted by this change
```
$ inv test --help
Usage: inv[oke] [--core-opts] test [--options] [other tasks here ...]
Docstring:
Run all tests.
Options:
-c, --coverage   True to generate coverage report using pytest-cov
-d, --doctest    True to run doctest modules, otherwise False.
```
- ~~[ ] I added a line to the `CHANGELOG.rst` file in the `Unreleased` …
=> Suggestion to add option to run pytest-cov through invoke test

pytest.ini, setup.cfg
Got confused when I couldn't find doctest_optionflags in setup.cfg, but then found them in pytest.ini. Is there a reason pytest is configured in two places? I might have misunderstood the setup though.
I also removed --doctest-modules from addopts since that's added to env on the linux travis job, and set by invoke test --doctest otherwise.
- ~~I added a line to the `CHANGELOG.rst` file in the `Unreleased` section under the most fitting heading (e.g. `Added`, `Changed`, `Removed`).~~
- ~~I added new functions/classes and made them available on a second-level import, e.g. `compas_fab.robots.Configuration`.~~
- ~~I have added tests that prove my fix is effective or that my feature works.~~
- ~~I have added necessary documentation (if appropriate)~~
=> Merge pytest.ini with setup.cfg, remove doctest opt in setup.cfg

CHANGELOG.rst, src/compas_fab/backends/ros/planner_backend_moveit.py
- Add `goal constraints` handling to `inverse_kinematics` of MoveIt planner.
- Add `trajectory_constraints` handling to `plan_cartesian_motion` of MoveIt planner.
- Refactor constraints conversion.
=> Convert constraints on IK and cartesian planner

requirements-dev.txt, setup.py
Builds fails because pytest specifies `attrs>=17.4.0` ([here](https://github.com/pytest-dev/pytest/blob/master/setup.py#L8)) while other compas_fab deps need 19.3.0 (e.g. six, twisted). By specifying `attrs` version in `requirements-dev.txt` we make sure we have the right version.
- CI bug fix
- ~~I added a line to the `CHANGELOG.rst` file in the `Unreleased` section under the most fitting heading (e.g. `Added`, `Changed`, `Removed`).~~
=> Solve Travis’ attrs version mismatch

CHANGELOG.rst, src/compas_fab/backends/ros/messages/moveit_msgs.py, src/compas_fab/robots/constraints.py
In :class:`compas_fab.robots.constraints.JointConstraint`, added `tolerance_above `and  `tolerance_below ` for allowing asymmetrical constraints. This also conforms to the JointConstraint ROS message:
http://docs.ros.org/kinetic/api/moveit_msgs/html/msg/JointConstraint.html
=> Joint constraint

setup.cfg
I'd like to ignore error D105, "Missing docstring in magic method" (i.e. `__repr__`, `__eq__` etc). There is not much to say about these functions, they are what they are. If this is rejected I'd suggest we define some standard docstrings for these methods.
=> pydocstyle ignore D100 ”Missing docstring in public module”

src/compas_fab/robots/constraints.py
Outdated workaround now that pinned version of compas has been bumped.
- ~~I added a line to the `CHANGELOG.rst` file in the `Unreleased` section under the most fitting heading (e.g. `Added`, `Changed`, `Removed`).~~
- ~~I added new functions/classes and made them available on a second-level import, e.g. `compas_fab.robots.Configuration`.~~
-  ~~I have added tests that prove my fix is effective or that my feature works.~~
- ~~I have added necessary documentation (if appropriate).~~
=> Revert workaround in compas.robots.OrientationConstraint.transform()

docs/conf.py
While working through docs I noticed that the lists of Attributes in the generated Sphinx documentation looked different compared to class documentation for Compas.
The difference comes from some patching of napoeleon (Sphinx extension) in `docs/conf.py` that @brgcode did. I copied this to compas_fab's `docs/conf.py`.
I also removed the option `'special-members': '__init__'` from  `autodoc_default_options`. The signature is already displayed at the top of the document. Having this option turned on results in the small init section at the bottom, and warnings like this while building the docs:
```
/[...]/compas_fab/src/compas_fab/robots/constraints.py:docstring of
compas_fab.robots.OrientationConstraint.__init__:1:
WARNING: duplicate object description of …
```
=> Fixes for class docs

.deepsource.toml
Would remove all these false positives: https://deepsource.io/gh/compas-dev/compas_fab/issue/BAN-B101/occurrences
=> deepsource: test_patterns needs to be relative to proj root

CHANGELOG.rst, docs/examples/02_description_models/02_robot.rst, docs/examples/02_description_models/files/02_robot_artist_blender.py, docs/examples/02_description_models/files/02_robot_artist_grasshopper.ghx, docs/examples/02_description_models/files/02_robot_artist_rhino.py, docs/examples/02_description_models/files/02_robot_artist_rhino_from_ros.py, docs/examples/03_backends_ros/files/robot-playground.ghx, setup.py, src/compas_fab/artists/__init__.py, src/compas_fab/artists/base.py, src/compas_fab/blender/__init__.py, src/compas_fab/blender/artists.py, src/compas_fab/ghpython/__init__.py, src/compas_fab/ghpython/artists.py, src/compas_fab/ghpython/path_planning.py, src/compas_fab/rhino/__init__.py, src/compas_fab/rhino/artists.py, src/compas_fab/robots/robot.py
First step before moving these artists up to `compas` core, they've been rename to `RobotModel` artists.
This is a breaking change, although a minor one. I created aliases to preserve the old names for a little longer, but the `self.robot` instance variable of artists has changed to `self.model` and there's no alias for it.
=> close #165: rename RobotArtist to RobotModelArtist

CHANGELOG.rst, docs/getting_started.rst, setup.py, src/compas_fab/__init__.py, src/compas_fab/rhino/install.py, src/compas_fab/rhino/uninstall.py
This PR uses the changes on https://github.com/compas-dev/compas/pull/614 to remove the install/uninstall scripts and instead use the new extension points.
=> Use new extension point for declaring rhino installable packages

CHANGELOG.rst, src/compas_fab/robots/robot.py
=> Configuration from group states

src/compas_fab/backends/pybullet/backend_features/pybullet_inverse_kinematics.py
The pybullet id of a joint is written into the model's joint attrs not the semantics joint attrs.
=> silly bugs

CHANGELOG.rst, setup.py
Preparing 0.13 release, it's a breaking change because 0.16->0.17 of compas is a breaking change on its own.
=> Bump compas dependency to 0.17

CHANGELOG.rst, src/compas_fab/backends/ros/service_description.py, src/compas_fab/robots/tool.py
This PR fixes two issues:
- Attaching a tool was using a `frame_id=None` depending on the order of operations, so now we ensure the frame id is rebuilt if tool name changes
- In some cases, IronPython uses an old-style class to represent the service response, which triggers an inner exception that is not handled and causes a freeze when used in GH.
=> Two fixes in one

src/compas_fab/backends/pybullet/const.py
Despite being lazy loaded, the `pybullet` library was loaded all the time due to the usage of some consts coming from the `pybullet` library, so instead of using them it's best to copy them.
=> Copy pybullet consts

src/compas_fab/backends/pybullet/backend_features/pybullet_add_attached_collision_mesh.py, src/compas_fab/backends/pybullet/backend_features/pybullet_forward_kinematics.py, src/compas_fab/backends/pybullet/backend_features/pybullet_inverse_kinematics.py
The pybullet docs suggest that the argument ``group`` is used in the calculation of ik/fk.  This is not the case.  I amended the docs to reflect this.  I also experimented with changing pybullet's ik to limit the calculation to a specific group without success.
Closes #229 
=> Fix pybullet docs

.github/workflows/pr-checks.yml, CHANGELOG.rst, setup.py
Update COMPAS dependency to the latest. It's not a breaking change on `fab`'s side but since it is on compas, I'm tagging it as such on our side as well.
=> Bump compas dependency to 0.18

CHANGELOG.rst, src/compas_fab/backends/__init__.py, src/compas_fab/robots/wrench.py
Totally insignificant PR to preemptively switch to `compas.IPY` since the function `is_ironpython` will go away from `compas` core.
=> Switch to use compas.IPY

CHANGELOG.rst, setup.py, src/compas_fab/backends/pybullet/client.py
To allow users to [#bugbash](https://github.com/compas-dev/compas/issues/694) using latest compas AND compas_fab:
=> Bump compas dependency to 0.19

CHANGELOG.rst, docs/examples/03_backends_ros/files/05_plan_cartesian_motion.py, src/compas_fab/backends/ros/backend_features/move_it_add_attached_collision_mesh.py, src/compas_fab/backends/ros/backend_features/move_it_plan_cartesian_motion.py, src/compas_fab/backends/ros/backend_features/move_it_plan_motion.py, src/compas_fab/backends/ros/backend_features/move_it_remove_attached_collision_mesh.py, src/compas_fab/backends/ros/messages/moveit_msgs.py, src/compas_fab/robots/planning_scene.py, src/compas_fab/robots/trajectory.py
Closes #263.  While I was doing this, I noticed a pretty serious bug introduced with version 0.12.  `RosClient.add_attached_collision_mesh` was adding a collision mesh, but not attaching it.  So that's fixed here too.  
=> Add attached collision meshes to joint trajectories

CHANGELOG.rst, src/compas_fab/backends/ros/messages/moveit_msgs.py
Why not inspect compas_fab for this bug too?
=> add __ne__ to PlanningSceneComponents

CHANGELOG.rst, src/compas_fab/backends/pybullet/backend_features/pybullet_inverse_kinematics.py, src/compas_fab/backends/pybullet/client.py, src/compas_fab/backends/ros/backend_features/helpers.py, src/compas_fab/backends/ros/backend_features/move_it_forward_kinematics.py, src/compas_fab/backends/ros/backend_features/move_it_inverse_kinematics.py, src/compas_fab/backends/ros/backend_features/move_it_plan_cartesian_motion.py, src/compas_fab/backends/ros/backend_features/move_it_plan_motion.py, src/compas_fab/backends/ros/client.py, src/compas_fab/backends/vrep/client.py, src/compas_fab/ghpython/components/compile.py, src/compas_fab/robots/configuration.py, src/compas_fab/robots/robot.py, src/compas_fab/robots/trajectory.py, tests/robots/test_configuration.py
This is an attempt to make `Configuration` behave in some ways like a read-only dictionary, returning a joint value for a joint name key.  It is also an attempt to make the attributes like `joint_names` and `joint_values` semi-immutable in the sense that their lengths cannot change but their values can.  `FixedLengthList` subclasses `list` and overwrites many methods.  Please look over that carefully, and suggest meaningful tests.  That class is defined in `configuration.py` because it will only be there for a hot minute.  It too will migrate to compas core.  I haven't added an entry to the changelog for the same reason.  But at the same time, I wonder where best to announce the breaking change of `values` to `joint_values`, and the removal of `merge`.  
PS.  I just noticed that as part …
=> Dictionary-like Configuration

CHANGELOG.rst, src/compas_fab/backends/ros/messages/moveit_msgs.py
Fixes bug where the header of a collision mesh is treated as a dictionary rather than a ROSmsg.  
=> fix use of getattr

CHANGELOG.rst, src/compas_fab/robots/planning_scene.py
The collision_mesh param is empty, but its root_name has been set already, so, instead we don't try to do reassign it, it will be deserialized from data.
=> When deserializing from data, ctor of ACM fails

CHANGELOG.rst, src/compas_fab/ghpython/components/install.py
Tiny PR: the list of `remove_symlinks` should only include targets, not sources. This causes a warning message when uninstalling.
=> Fix error messages on uninstall

CHANGELOG.rst, src/compas_fab/backends/pybullet/client.py
Closes #305   PyBullet, by default, caches the contents of obj's that it has loaded.  If it encounters a recognized path to an obj, it assumes the contents are the same as when it first read it.  Previously all the meshes were stored in `some/temp/dir/temp.obj`.  Now they will be stored in `some/temp/dir/{mesh.guid}.obj`.   I don't want to disable cacheing entirely, because that would effect performance.  I also don't want to return to having a new temp dir every time `convert_mesh_to_body` is called, because that is essentially turning off cacheing.  @gonzalocasas is this sufficient?  Given the way `mesh.uuid` is created (that is, lazily created when `guid` is called, but not modified when the mesh changes), the problem still exists for the following code:
```
from compas.datastructures …
```
=> Change temp file name in convert_mesh_to_body

CHANGELOG.rst, src/compas_fab/backends/pybullet/client.py, src/compas_fab/robots/semantics.py
Addresses #318 
Following the discussion in the above mentioned issue, I've added a new property `unordered_disabled_collisions` which is a set of frozensets with the same data as in the usual `disabled_collisions` which is a set of tuples.  This is backward compatible and keeps the existing code clean.  Now `pybullet_client.disabled_collisions = semantics.disabled_collisions` will behave as desired.  I didn't add a more broad function to add semantic data to the pybullet client because currently group support in pybullet is a bit hacky and I don't want make it seem otherwise ;)
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going …
=> Adds unordered_disabled_collisions to PyBulletClient and RobotSemantics

tasks.py
Fix the local build ghuser task to match what compas core does now. See https://github.com/compas-dev/compas/pull/949
=> Fix the ghuser component build task fetch GHIO lib from NuGet

CHANGELOG.rst, src/compas_fab/ghpython/components/Cf_ConstraintsFromPlane/metadata.json, src/compas_fab/ghpython/components/Cf_InverseKinematics/metadata.json, src/compas_fab/ghpython/components/Cf_PlanCartesianMotion/metadata.json, src/compas_fab/ghpython/components/Cf_PlanMotion/metadata.json, src/compas_fab/ghpython/components/Cf_PlanningScene/metadata.json, src/compas_fab/ghpython/components/Cf_VisualizeRobot/metadata.json, src/compas_fab/ghpython/components/Cf_VisualizeTrajectory/metadata.json
I usually spend more-than-desirable time during workshops cleaning up Grasshopper examples because the wires connecting to `robot` are such a mess. So, instead of that, we could default to `hidden`.
=> Default to hide robot wires

CHANGELOG.rst, src/compas_fab/backends/ros/backend_features/move_it_add_attached_collision_mesh.py, src/compas_fab/backends/ros/backend_features/move_it_add_collision_mesh.py, src/compas_fab/backends/ros/backend_features/move_it_append_collision_mesh.py, src/compas_fab/backends/ros/backend_features/move_it_remove_attached_collision_mesh.py, src/compas_fab/backends/ros/backend_features/move_it_remove_collision_mesh.py, src/compas_fab/backends/ros/backend_features/move_it_reset_planning_scene.py, src/compas_fab/backends/ros/client.py, src/compas_fab/backends/ros/messages/moveit_msgs.py
The lack of the `pose` field in ROS noetic caused it to ignore the frame of the collision meshes (it complains about empty quaternions)
=> fix: pose of collision meshes was ignored in ROS Noetic

CHANGELOG.rst, src/compas_fab/ghpython/components/Cf_VisualizeRobot/code.py
* Fixed link parameter name when doing FK inside the GH component to display attached collision meshes.
* Fixed transform of the attached collision mesh frame inside the GH component.
=> Fix two ACM display bugs

CHANGELOG.rst, src/compas_fab/ghpython/components/install.py
The uninstaller was pointing to the wrong directory, so it doesn't uninstall anything. Now it should be correct.
=> Fix uninstall of GH components

CHANGELOG.rst, docs/backends/vrep.rst, docs/developer/grasshopper.rst
Added some missing information to Grasshopper and V-REP doc pages.
=> added some missing information to GH and v-rep docs

CHANGELOG.rst, docs/examples/03_backends_ros/02_robot_models.rst, docs/examples/03_backends_ros/03_forward_and_inverse_kinematics.rst, docs/examples/03_backends_ros/04_plan_motion.rst, docs/examples/03_backends_ros/05_collision_objects.rst, src/compas_fab/backends/kinematics/solvers/offset_wrist.py, src/compas_fab/backends/kinematics/utils.py, src/compas_fab/ghpython/components/Cf_AttachTool/code.py, src/compas_fab/ghpython/components/Cf_VisualizeRobot/code.py, src/compas_fab/ghpython/components/Cf_VisualizeRobot/metadata.json
This change (finally) adds supports for all the planning scene elements to be visualized with the default `Robot Visualize` component of Grasshopper. This means both attached and non-attached collision meshes will be retrieved and shown and there's no need to pass them to the component explicitly anymore.
Here's a quick screenshot showing the component in action with both an ACM and a CM:
It also changes the behavior of the `Attach tool` component that was (needlessly) adding the tool meshes to the planning scene, but they can be an in-memory thing only.
And a bunch of typos as well.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are …
=> Planning scene viz

CHANGELOG.rst, src/compas_fab/backends/ros/backend_features/move_it_forward_kinematics.py, src/compas_fab/backends/ros/backend_features/move_it_inverse_kinematics.py, src/compas_fab/backends/ros/backend_features/move_it_plan_cartesian_motion.py, src/compas_fab/backends/ros/backend_features/move_it_plan_motion.py, src/compas_fab/backends/ros/messages/moveit_msgs.py
This PR fixes support for ROS Kinetic when using FK, IK, plan cartesian and plan free-space motion. There was already a similar fix in place for all the planning scene operations, but it was not copied for the other backend features.
=> Fix kinetic support

pyproject.toml, requirements-dev.txt, setup.cfg, tasks.py
First added the max line length to `black` settings in a new `pyproject.toml` and then moved most of the settings from `setup.cfg` to `pyproject.toml`. I tried to move `bdist_wheel` setting but it didn't seem to use it even though it is technically supported (I might have missed another setting to trigger that?), and then `flake8` would be the other one remaining, which doesn't officially support `pyproject.toml`, but we should replace with `black`.
=> Moving most config to pyproject.toml

CHANGELOG.rst, src/compas_fab/ghpython/components/Cf_RosTopicPublish/code.py
If the `ros client` of a topic instance changes in Grasshopper, for example, if a new ROS connect component is connected to it, it needs to detect the instance is not the same and re-start the advertise operation before publishing.
This was found by @kunaalchadha and we tested the fix on his machine.
=> Re-advertise topic if the ros client has changed

.github/workflows/build.yml, .github/workflows/deploy-n-publish.yml, .github/workflows/integration.yml, CHANGELOG.md, src/compas_fab/ghpython/components/Cf_VisualizeRobot/code.py
This is a small but noticeable performance optimization when there are lots of collision meshes in the scene. It prevents the retrieval and reloading of the scene constantly, and instead caches it for a couple of seconds. 
This very short cache is enough to prevent reloading while the user is, eg. dragging a slider to update the robot:
=> Add scene cache to 'Visualize Robot" component

CHANGELOG.md, src/compas_fab/robots/planning_scene.py, src/compas_fab/robots/robot.py, src/compas_fab/robots/semantics.py, src/compas_fab/robots/tool.py, tests/robots/test_robot.py
Some of the classes in compas_fab is still based on (object) instead of (Data)
I have selected some of the classes that should support serialization and upgrade them. Upgrading them should be backward compatible. However, it may affect user classes inherited from these classes. This RP does not cover all the classes yet (e.g. classes in backends, reachability map, ghpython and some more). Let me know if you think I should extend to cover all classes. 
@gonzalocasas Should I add test files for this? 
=> Changed classes to inherete from compas.Data

CHANGELOG.md, src/compas_fab/backends/__init__.py, src/compas_fab/backends/exceptions.py, src/compas_fab/backends/interfaces/client.py, src/compas_fab/ghpython/components/Cf_VisualizeRobot/code.py
Without a specific exception, the "visualize robot" component cannot know why the planning scene part is failing when using the analytical IK solvers. So, this adds a new exception type and the component now checks for it and does not fail in that case, it simply disables showing things that will not work.
=> Raise specific exceptions if backend feature is not supported

CHANGELOG.md, src/compas_fab/robots/time_.py, tests/robots/test_duration.py
Changed the behavior of Duration class when accepting both seconds (float) and nanoseconds (int) where the decimal point of seconds and the nanoseconds add up to more than 1 second.
In the following test (existing), the total duration is expected to be 3.1 seconds. 
```
def test_sec_remainder_add_to_nsec():
d = Duration(2.6, 5e8)
assert d.seconds == 3.1
```
However, existing implementation did not carry on the values from nsec to sec when the total value adds up.  The following test explains the more desirable behavior:
```
def test_sec_remainder_add_to_nsec():
d = Duration(2.6, 5e8)
assert d.secs == 3
assert d.nsecs == 1e8
assert d.seconds == 3.1
```
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate …
=> Fix Addition error in Duration() 

src/compas_fab/__init__.py, src/compas_fab/backends/interfaces/backend_features.py, src/compas_fab/backends/kinematics/analytical_plan_cartesian_motion.py, src/compas_fab/backends/ros/backend_features/move_it_plan_cartesian_motion.py, src/compas_fab/backends/ros/client.py, src/compas_fab/robots/planning_scene.py, src/compas_fab/robots/robot.py, src/compas_fab/robots/semantics.py, src/compas_fab/robots/time_.py, src/compas_fab/robots/tool.py, src/compas_fab/robots/trajectory.py, tests/robots/test_duration.py
=> Clean up the broken Class and Function links in docstrings

.github/workflows/ironpython.yml
This is to temporarily avoid problem with the IPY workflow.
See this failed action for example:
https://github.com/compas-dev/compas_fab/actions/runs/9294697625/job/25580341228#step:3:837
=> Pin compas version in ironpython workflow

CHANGELOG.md, docs/examples/02_description_models/03_targets.rst, docs/examples/03_backends_ros/files/04_plan_cartesian_motion.py, docs/examples/03_backends_ros/files/gh_plan_cartesian_motion.py, docs/examples/06_backends_kinematics/files/04_cartesian_path_analytic_pybullet.py, src/compas_fab/backends/interfaces/backend_features.py, src/compas_fab/backends/kinematics/analytical_plan_cartesian_motion.py, src/compas_fab/backends/ros/backend_features/move_it_plan_cartesian_motion.py, src/compas_fab/ghpython/components/Cf_PlanCartesianMotion/code.py, src/compas_fab/robots/robot.py, src/compas_fab/robots/targets.py, tests/backends/kinematics/test_inverse_kinematics.py, tests/robots/test_targets.py
This is a short PR to migrate the plan_cartrsian_motion to use Waypoints class.
At the moment, only the FrameWaypoints are supported as no implementation is added for PointAxisWaypoints yet. Will do that in next PR.
- [] New feature in a **backwards-compatible** manner.
=> Plan_cartesian_motion uses Waypoints class

src/compas_fab/robots/robot.py
=> refactor: Use TOL.is_close for checking if scaling is needed in Robot class

CHANGELOG.md, docs/developer/backends.rst, src/compas_fab/backends/interfaces/__init__.py, src/compas_fab/backends/interfaces/backend_features.py, src/compas_fab/backends/interfaces/client.py, src/compas_fab/backends/pybullet/backend_features/__init__.py, src/compas_fab/backends/pybullet/backend_features/pybullet_add_attached_collision_mesh.py, src/compas_fab/backends/pybullet/backend_features/pybullet_add_collision_mesh.py, src/compas_fab/backends/pybullet/backend_features/pybullet_append_collision_mesh.py, src/compas_fab/backends/pybullet/backend_features/pybullet_forward_kinematics.py, src/compas_fab/backends/pybullet/backend_features/pybullet_inverse_kinematics.py, src/compas_fab/backends/pybullet/backend_features/pybullet_remove_attached_collision_mesh.py, src/compas_fab/backends/pybullet/backend_features/pybullet_remove_collision_mesh.py, src/compas_fab/backends/pybullet/client.py, src/compas_fab/backends/pybullet/planner.py, src/compas_fab/backends/ros/backend_features/__init__.py, src/compas_fab/backends/ros/backend_features/move_it_add_attached_collision_mesh.py, src/compas_fab/backends/ros/backend_features/move_it_add_collision_mesh.py, src/compas_fab/backends/ros/backend_features/move_it_append_collision_mesh.py, src/compas_fab/backends/ros/backend_features/move_it_forward_kinematics.py, src/compas_fab/backends/ros/backend_features/move_it_inverse_kinematics.py, src/compas_fab/backends/ros/backend_features/move_it_plan_cartesian_motion.py, src/compas_fab/backends/ros/backend_features/move_it_plan_motion.py, src/compas_fab/backends/ros/backend_features/move_it_planning_scene.py, src/compas_fab/backends/ros/backend_features/move_it_remove_attached_collision_mesh.py, src/compas_fab/backends/ros/backend_features/move_it_remove_collision_mesh.py, src/compas_fab/backends/ros/backend_features/move_it_reset_planning_scene.py, src/compas_fab/backends/ros/planner.py, tests/robots/test_robot.py
A continuation of #424 after I messed things up.
=> Remove Planner call magic, using multi-inherence instead.

CHANGELOG.md, src/compas_fab/backends/kinematics/analytical_inverse_kinematics.py, src/compas_fab/backends/pybullet/backend_features/pybullet_add_attached_collision_mesh.py, src/compas_fab/backends/pybullet/backend_features/pybullet_forward_kinematics.py, src/compas_fab/backends/pybullet/backend_features/pybullet_inverse_kinematics.py, src/compas_fab/backends/pybullet/backend_features/pybullet_remove_attached_collision_mesh.py, src/compas_fab/backends/pybullet/client.py
The existing naming convention calling the cached robot_model as robot is very confusing. I renamed it to explicitly say `cached_robot_model`.
This is a breaking change for people who directly access the cached model, but I doubt anyone is doing that now.
- `PybulletClient.get_cached_robot` to `PybulletClient.get_cached_robot_model`
- `PybulletClient.ensure_cached_robot` to `PybulletClient.ensure_cached_robot_model`.
- `PybulletClient.ensure_cached_robot_geometry` to `PybulletClient.ensure_cached_robot_model_geometry`.
- `PybulletClient.cache_robot` to `PybulletClient.cache_robot_model`.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we …
=> Renamed a bunch of `cached_robot` to `cached_robot_model` in PyBulletClient

CHANGELOG.md, requirements.txt, src/compas_fab/backends/ros/client.py
=> Change planner type arg
